### ISSUE TITLE
Retours

### ISSUE THREAD

**Issue by bertrandjamin** [at69/monitor_availability#2]
Salut Alban, voici quelques retours sur ton projet : 

### composer 

Tu n'as pas commité le `composer.lock` attention ce fichier est très important pour locker les versions des dépendences utilisées par le projet.

### Schema  SQL

J'aimais bien l'idée des dispo par ville pour les moniteurs. 
Mais j'aurais créé une liaison OneToMany entre les tables `monitor`et `availability` (pour permettre aux moniteurs de mettre de dispos sur plusieurs villes...

### Controller

* Juste par habitude évite de commiter des données inutiles (ex : ` DefaultController.php`) ça fait du bruit pour rien :) 
* Il y a trop de logique dans ton `MonitorController` l'organisation à privilégier est de déplacer toute la construction de la requête dans le `MonitorRepository` (http://symfony.com/doc/current/doctrine.html#organizing-custom-queries-into-repository-classes)
* Personnellement j'aurais notamment séparé les check de paramètres (via  https://symfony.com/doc/current/validation.html) et la construction de la requête dans le `MonitorRepository`
* Tu n'utilises que des REGEXP et à lire tes conditions il semble qu'il faille une égalité parfaite pour que le filtre fonctionne, préfère le classic `LIKE '%%' ` (sauf si tu as une bonne raison et là je suis curieux :) )

### Repository 

* Ils sont donc vide :o ;)

### Service

Je n'ai pas compris l'utilité de tes Manager qui semble agirent comme des proxies pour les Repository associés...
Mais ils ne semble pas vraiment avoir d'utilité....

**Comment by at69** [comment]
### composer 

OK!

### Schema  SQL

Mon schéma autorise un moniteur à avoir des disponibilités sur plusieurs villes. Tu peux d'ailleurs le voir dans les données dans l'export SQL que je t'ai envoyé. J'ai peut-être mal retranscrit la relation dans le code? Je vérifierai!

### Controller

OK! 
Pour les regex, ils permettent d'aller plus loin que le LIKE. Par exemple de chercher tous les moniteurs dont le nom commence par A et se termine par n. Il est cependant vrai qu'en y réfléchissant rapidement, je ne vois pas de cas business où l'usage du like ne suffirait pas.
L’enchaînement de mes conditions de filtrage est effectivement perfectible. 

### Service

La formation Symfony que j'avais faite était peu efficace pour montrer l'utilité des services. Il faut que j'étudie de meilleurs cas d'utilisation.
